apiVersion: v1
kind: Namespace
metadata:
  labels:
    controller: image-clone-controller
  name: image-controller
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: image-controller
data:
  registry-username: dXNlcm5hbWU=
  registry-passowrd: cGFzc3dvcmQ=